(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'results' is not defined"
p3
sS'layer'
p4
S'/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f6b892d2e30, file "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ria/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 8, in <module>\n  File "/home/ria/Desktop/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 6, in result1\n    return dict(results=results)\nNameError: global name \'results\' is not defined\n'
p11
s.